In [1]:
def Display_Board(Arr, i):
  print("Move No: " + str(i))
  print()
  print(" #", Arr[0][0], "|", Arr[0][1], "|", Arr[0][2], "#")
  print("---------------")
  print(" #", Arr[1][0], "|", Arr[1][1], "|", Arr[1][2], "#")
  print("---------------")
  print(" #", Arr[2][0], "|", Arr[2][1], "|", Arr[2][2], "#")

In [7]:
Arr = []
for i in range(3):
  Arr.append(['0', '0', '0'])
Display_Board(Arr, 0)

Move No: 0

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #


In [86]:
def Toss():
  Number = random.randint(1, 2)
  if(Number == 1):
    return "Computer"
  else:
    return "Human"

In [2]:
def Row_Check(A):
  Winner = "No Body"
  for i in range(3):
    if((A[i][0] == A[i][1]) and (A[i][0] == A[i][2])):
      if(A[i][0] == 'X'):
        Winner = "Human"
        return True, Winner
      elif(A[i][0] == 'O'):
        Winner = "Computer"
        return True, Winner
  return False, Winner

In [3]:
def Column_Check(A):
  Winner = "No Body"
  for i in range(3):
    if((A[0][i] == A[1][i]) and (A[0][i] == A[2][i])):
      if(A[0][i] == 'X'):
        Winner = "Human"
        return True, Winner
      elif(A[0][i] == 'O'):
        Winner = "Computer"
        return True, Winner
  return False, Winner

In [4]:
def Digonal_Check(A):
  Winner = "No Body"
  if((A[0][0] == A[1][1]) and (A[0][0] == A[2][2])):
    if(A[0][0] == 'X'):
      Winner = "Human"
      return True, Winner
    elif(A[0][0] == 'O'):
      Winner = "Computer"
      return True, Winner
  elif((A[0][2] == A[1][1]) and (A[0][2] == A[2][0])):
    if(A[0][2] == 'X'):
      Winner = "Human"
      return True, Winner
    elif(A[0][2] == 'O'):
      Winner = "Computer"
      return True, Winner
  return False, Winner

In [5]:
def Check_Win(Arr):
  Game_Over = False
  Winner = "No Body"
  Game_Over_1, Winner_1 = Row_Check(Arr)
  Game_Over_2, Winner_2 = Column_Check(Arr)
  Game_Over_3, Winner_3 = Digonal_Check(Arr)
  if(Game_Over_1 or Game_Over_2 or Game_Over_3):
    Game_Over = True
    if(Game_Over_1):
      Winner = Winner_1
    elif(Game_Over_2):
      Winner = Winner_2
    else:
      Winner = Winner_3
  return Game_Over, Winner

In [8]:
Game_Over, Winner = Check_Win(Arr)
print(Game_Over, Winner)

False No Body


In [84]:
import random
def Computer_Move(Arr):
  X = random.randint(0, 2)
  Y = random.randint(0, 2)
  while(Arr[X][Y] != '0'):
    X = random.randint(0, 2)
    Y = random.randint(0, 2)
  Arr[X][Y] = 'O'
  return Arr

In [10]:
def Player_Move(Arr):
  X, Y = list(map(int, input().split()))
  Arr[X][Y] = 'X'
  return Arr

In [14]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [12]:
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(9, input_shape = [9], activation = 'relu', name = "Layer_1"),
                                    tf.keras.layers.Dense(1, activation = 'softmax')
])
model.compile(optimizer = 'adam', loss = 'mse', metrics = ['accuracy', 'mse'])

In [ ]:
Train_X = []
Train_Y = []
Arr = []
for i in range(3):
  Arr.append(['0', '0', '0'])
i = 1
Game_Over = False
Display_Board(Arr,  0)
while((Game_Over != True) and i <= 9):
  Arr = Computer_Move(Arr)
  Train_X.append(sum(Arr, []))
  Display_Board(Arr, i)
  i = i + 1
  Game_Over, Winner = Check_Win(Arr)
  if(Game_Over == False):
    Arr = Player_Move(Arr)
    Game_Over, Winner = Check_Win(Arr)
    Display_Board(Arr, i)
    Train_X.append(sum(Arr, []))
    i = i + 1
if(Game_Over == False):
  print(Draw)
  for j in range(i):
    Train_Y.append(0)
elif(Game_Over == True):
  print(Winner)
  for j in range(i - 1):
    if(Winner == 'Human'):
      Train_Y.append(-1)
    else:
      Train_Y.append(1)

Move No: 0

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
Move No: 1

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | O | 0 #
2 2
Move No: 2

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | O | X #
Move No: 3

 # 0 | 0 | 0 #
---------------
 # 0 | O | 0 #
---------------
 # 0 | O | X #
1 2
Move No: 4

 # 0 | 0 | 0 #
---------------
 # 0 | O | X #
---------------
 # 0 | O | X #
Move No: 5

 # 0 | 0 | O #
---------------
 # 0 | O | X #
---------------
 # 0 | O | X #
2 0
Move No: 6

 # 0 | 0 | O #
---------------
 # 0 | O | X #
---------------
 # X | O | X #
Move No: 7

 # 0 | O | O #
---------------
 # 0 | O | X #
---------------
 # X | O | X #
Computer


In [ ]:
for i in range(len(Train_X)):
  for j in range(len(Train_X[i])):
    if(Train_X[i][j] == '0'):
      Train_X[i][j] = 0
    elif(Train_X[i][j] == 'X'):
      Train_X[i][j] = -1
    else:
      Train_X[i][j] = 1
Train_X

[[0, 0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, -1],
 [0, 0, 0, 0, 1, 0, 0, 1, -1],
 [0, 0, 0, 0, 1, -1, 0, 1, -1],
 [0, 0, 1, 0, 1, -1, 0, 1, -1],
 [0, 0, 1, 0, 1, -1, -1, 1, -1],
 [0, 1, 1, 0, 1, -1, -1, 1, -1]]

In [ ]:
Train_Y

[1, 1, 1, 1, 1, 1, 1]

In [ ]:
model.fit(Train_X, Train_Y, epochs = 2)

Epoch 1/2
1/1 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - mse: 0.0000e+00
Epoch 2/2
1/1 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 1.0000 - mse: 0.0000e+00


In [ ]:
Weights = model.layers[0].get_weights()

In [ ]:
Weights

[array([[-0.08324626,  0.26803643, -0.43723637,  0.05652064,  0.30163497,
         -0.35748273, -0.5170228 , -0.26723364,  0.36699253],
        [ 0.13872361, -0.2696314 , -0.05005473, -0.24906659, -0.22170281,
         -0.11982909, -0.45797625,  0.5357492 , -0.10365286],
        [-0.44256952,  0.5336232 ,  0.04776531, -0.3345731 , -0.46470326,
          0.42481267,  0.45187438,  0.00298536, -0.22374308],
        [ 0.15094107, -0.06791842, -0.4401909 ,  0.5649985 ,  0.26897615,
         -0.5333973 , -0.08717564,  0.5537528 ,  0.3558004 ],
        [ 0.40586996,  0.427096  ,  0.16764987, -0.3531915 ,  0.23370844,
          0.16845238, -0.01224244,  0.08065921, -0.2770351 ],
        [-0.02629793,  0.21671927, -0.5567778 ,  0.3116389 ,  0.11487502,
          0.39335805, -0.37860847,  0.1451428 ,  0.06146669],
        [-0.55375755, -0.17853352, -0.42054632,  0.33050716,  0.05432427,
         -0.31617105, -0.34356374, -0.00135547,  0.40560198],
        [ 0.4417429 ,  0.4667703 ,  0.22772282, 

In [ ]:
import numpy as np
Weights = np.array(Weights[0])

In [ ]:
Weights

array([[-0.08324626,  0.26803643, -0.43723637,  0.05652064,  0.30163497,
        -0.35748273, -0.5170228 , -0.26723364,  0.36699253],
       [ 0.13872361, -0.2696314 , -0.05005473, -0.24906659, -0.22170281,
        -0.11982909, -0.45797625,  0.5357492 , -0.10365286],
       [-0.44256952,  0.5336232 ,  0.04776531, -0.3345731 , -0.46470326,
         0.42481267,  0.45187438,  0.00298536, -0.22374308],
       [ 0.15094107, -0.06791842, -0.4401909 ,  0.5649985 ,  0.26897615,
        -0.5333973 , -0.08717564,  0.5537528 ,  0.3558004 ],
       [ 0.40586996,  0.427096  ,  0.16764987, -0.3531915 ,  0.23370844,
         0.16845238, -0.01224244,  0.08065921, -0.2770351 ],
       [-0.02629793,  0.21671927, -0.5567778 ,  0.3116389 ,  0.11487502,
         0.39335805, -0.37860847,  0.1451428 ,  0.06146669],
       [-0.55375755, -0.17853352, -0.42054632,  0.33050716,  0.05432427,
        -0.31617105, -0.34356374, -0.00135547,  0.40560198],
       [ 0.4417429 ,  0.4667703 ,  0.22772282, -0.41940123,  0

In [ ]:
def Computer(Arr, Weights):
  Input = []
  for i in range(len(Arr)):
    for j in range(len(Arr[0])):
      if(Arr[i][j] == 'O'):
        Input.append(2)
      elif(Arr[i][j] == 'X'):
        Input.append(-2)
      else:
        Input.append(0)
  # for i in range(len(Input)):
  #   for j in range(len(Input[i])):
  #     if(Input[i][j] == '0'):
  #       Input[i][j] = 0
  #     elif(Input[i][j] == 'X'):
  #       Input[i][j] = -1
  #     else:
  #       Input[i][j] = 1
  # Temp = sum(Input, [])
  Input = np.array(Input)
  Input.reshape((1, 9))
  Array = np.dot(Input, Weights)
  for i in range(9):
    if(Input[i] != 0):
      Array[i] = 0
  Position = np.argmax(Array)
  X = Position//3
  Y = Position - 3*X
  Arr[X][Y] = 'O'
  return Arr

In [ ]:
Arr

[['0', 'O', 'O'], ['0', 'O', 'X'], ['X', 'O', 'X']]

In [ ]:
Array = Computer(Arr, Weights)

In [ ]:
Array

array([ 1.18787971,  0.6420128 ,  1.06290284, -1.68057898, -0.12928876,
        0.62489367,  1.24885315,  0.104884  , -0.85108596])

In [ ]:
Arr

[[0, 1, 1], [0, 1, -1], [-1, 1, -1]]

In [ ]:
for i in range(3):
  for j in range(3):
    if(Arr[i][j] != 0):
      Array[3*i + j] = 0

In [ ]:
Array

array([ 1.18787971,  0.        ,  0.        , -1.68057898,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [ ]:
Train_X = []
Train_Y = []
Arr = []
for i in range(3):
  Arr.append(['0', '0', '0'])
i = 1
Game_Over = False
Display_Board(Arr,  0)
while((Game_Over != True) and i <= 9):
  Arr = Computer(Arr, Weights)
  Train_X.append(sum(Arr, []))
  Display_Board(Arr, i)
  i = i + 1
  Game_Over, Winner = Check_Win(Arr)
  if(Game_Over == False):
    Arr = Player_Move(Arr)
    Game_Over, Winner = Check_Win(Arr)
    Display_Board(Arr, i)
    Train_X.append(sum(Arr, []))
    i = i + 1
if(Game_Over == False):
  print(Draw)
  for j in range(i):
    Train_Y.append(0)
elif(Game_Over == True):
  print(Winner)
  for j in range(i - 1):
    if(Winner == 'Human'):
      Train_Y.append(-1)
    else:
      Train_Y.append(1)


for i in range(len(Train_X)):
  for j in range(len(Train_X[i])):
    if(Train_X[i][j] == '0'):
      Train_X[i][j] = 0
    elif(Train_X[i][j] == 'X'):
      Train_X[i][j] = -2
    else:
      Train_X[i][j] = 2
model.fit(Train_X, Train_Y, epochs = 2)
Weights = model.layers[0].get_weights()
Weights = np.array(Weights[0])

Move No: 0

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
Move No: 1

 # O | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
2 2
Move No: 2

 # O | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | X #
Move No: 3

 # O | 0 | 0 #
---------------
 # 0 | O | 0 #
---------------
 # 0 | 0 | X #
0 2
Move No: 4

 # O | 0 | X #
---------------
 # 0 | O | 0 #
---------------
 # 0 | 0 | X #
Move No: 5

 # O | 0 | X #
---------------
 # O | O | 0 #
---------------
 # 0 | 0 | X #
1 2
Move No: 6

 # O | 0 | X #
---------------
 # O | O | X #
---------------
 # 0 | 0 | X #
Human
Epoch 1/2
1/1 [==============================] - 0s 1ms/step - loss: 4.0000 - accuracy: 0.0000e+00 - mse: 4.0000
Epoch 2/2
1/1 [==============================] - 0s 1ms/step - loss: 4.0000 - accuracy: 0.0000e+00 - mse: 4.0000


In [ ]:
Arr = Computer([['0', '0', 'O'], ['O', '0', '0'], ['X', 'X', '0']], Weights)

(9,)


In [ ]:
Arr

[['0', '0', 'O'], ['O', '0', 'O'], ['X', 'X', '0']]

In [15]:
model_1 = tf.keras.models.Sequential([
                                      tf.keras.layers.Dense(18, input_shape = [9], activation = 'relu'),
                                      tf.keras.layers.Dropout(0.1),
                                      tf.keras.layers.Dense(9, activation = 'relu'),
                                      tf.keras.layers.Dropout(0.1),
                                      tf.keras.layers.Dense(1, activation = "sigmoid")
])

In [17]:
model_1.compile(optimizer = tf.keras.optimizers.SGD(lr = 0.001), loss = 'mean_squared_error', metrics = ['accuracy', 'mean_squared_error'])

In [54]:
import numpy as np

In [69]:
def Computer_MOVE(Arr, model):
  Input = sum(Arr, [])
  Possible_Inputs = []
  for i in range(9):
    Temp = Input.copy()
    if(Input[i] == '0'):
      Temp[i] = 'O'
      Possible_Inputs.append(Temp)
  for i in range(len(Possible_Inputs)):
    for j in range(len(Possible_Inputs[0])):
      if(Possible_Inputs[i][j] == 'X'):
        Possible_Inputs[i][j] = -1
      elif(Possible_Inputs[i][j] == 'O'):
        Possible_Inputs[i][j] = 1
      else:
        Possible_Inputs[i][j] = 0
  Prediction = model.predict(Possible_Inputs)
  Position = np.argmax(Prediction)
  Next = Possible_Inputs[Position]
  Next_Outcome = []
  for i in range(3):
    Temp = []
    for j in range(3):
      if(Next[3*i + j] == 1):
        Temp.append('O')
      elif(Next[3*i + j] == -1):
        Temp.append('X')
      else:
        Temp.append('0')
    Next_Outcome.append(Temp)
  return Next_Outcome

In [70]:
Next_Outcome = Computer_MOVE([['0', '0', 'O'], ['O', '0', 'O'], ['X', 'X', '0']], model_1)

In [51]:
Possible

[['O', '0', 'O', 'O', '0', 'O', 'X', 'X', '0'],
 ['0', 'O', 'O', 'O', '0', 'O', 'X', 'X', '0'],
 ['0', '0', 'O', 'O', 'O', 'O', 'X', 'X', '0'],
 ['0', '0', 'O', 'O', '0', 'O', 'X', 'X', 'O']]

In [29]:
Input

['0', '0', 'O', 'O', '0', 'O', 'X', 'X', '0']

In [30]:
Input[0]

'0'

In [71]:
Next_Outcome

[['0', '0', 'O'], ['O', 'O', 'O'], ['X', 'X', '0']]

In [82]:
Train_X = []
Train_Y = []
Arr = []
for i in range(3):
  Arr.append(['0', '0', '0'])
i = 1
Game_Over = False
Display_Board(Arr,  0)
while((Game_Over != True) and i < 9):
  Arr = Computer_MOVE(Arr, model_1)
  Train_X.append(sum(Arr, []))
  Display_Board(Arr, i)
  i = i + 1
  Game_Over, Winner = Check_Win(Arr)
  if(Game_Over == False):
    Arr = Player_Move(Arr)
    Game_Over, Winner = Check_Win(Arr)
    Display_Board(Arr, i)
    Train_X.append(sum(Arr, []))
    i = i + 1
if(Game_Over == False):
  print("Draw")
elif(Game_Over == True):
  print(Winner)

for i in range(len(Train_X)):
  for j in range(len(Train_X[i])):
    if(Train_X[i][j] == '0'):
      Train_X[i][j] = 0
    elif(Train_X[i][j] == 'X'):
      Train_X[i][j] = -2
    else:
      Train_X[i][j] = 2
if(Winner == "Draw"):
  for i in range(len(Train_X)):
    Train_Y.append(0)
elif(Winner == 'Human'):
  for i in range(len(Train_X)):
    Train_Y.append(-1)
else:
  for i in range(len(Train_X)):
    Train_Y.append(1)
model_1.fit(Train_X, Train_Y, epochs = 2)

Move No: 0

 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
---------------
 # 0 | 0 | 0 #
Move No: 1

 # 0 | 0 | 0 #
---------------
 # 0 | O | 0 #
---------------
 # 0 | 0 | 0 #


KeyboardInterrupt: ignored