<a href="https://colab.research.google.com/github/amanjain252002/Tic-Tac-Toe/blob/main/TicTacToe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import numpy as np
import random

In [129]:
def toss():
  toss = random.randint(0,1)
  return toss

In [130]:
def status(board):
  for i in range(3):
    if((sum(board[i])==3) or (sum((board.T)[i])==3)):
      return 1
    elif((sum(board[i])==0) or (sum((board.T)[i])==0)):
      return 0
  if((sum(np.diag(board))==3) or (sum(np.diag(np.fliplr(board)))==3)):
    return 1
  elif((sum(np.diag(board))==0) or (sum(np.diag(np.fliplr(board)))==0)):
    return 0
  else:
    return -3

In [143]:
def bot():
  return random.randint(0,2), random.randint(0,2)

In [158]:
def legal(x,y,act_player,board):
  if(board[x,y] == -3):
    board[x,y] = act_player
  else:
    print("Not A Legal Move")
  return board

In [164]:
def play():
  board = np.full((3,3),-3)
  act_player = toss()
  n=9
  while(n!=0):
    if(status(board) == -3):
      if(act_player == 1):
        print("Enter the coord . Ex : 0 2 or 1 1")
        print("MOVE: #",(10-n))
        print(board)
        px, py = list(map(int,input().split()))
        board = legal(px,py,act_player,board)
        act_player = 0
      elif(act_player == 0):
        print("Enter the coord . Ex : 0 2 or 1 1")
        print("MOVE: #",(10-n))
        print(board)
        bx, by = bot()
        board = legal(bx,by,act_player,board)
        act_player = 1
      n-=1
    else:
      print(board)
      if(status(board)==1):
        print("WINNER WINNER CHICKEN DINNER")
      elif(status(board)==0):
        print("YOU BETTER DIE")
      break

In [165]:
play()

Enter the coord . Ex : 0 2 or 1 1
MOVE: # 1
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
Enter the coord . Ex : 0 2 or 1 1
MOVE: # 2
[[-3 -3 -3]
 [-3 -3 -3]
 [-3  0 -3]]
0 0
Enter the coord . Ex : 0 2 or 1 1
MOVE: # 3
[[ 1 -3 -3]
 [-3 -3 -3]
 [-3  0 -3]]
Enter the coord . Ex : 0 2 or 1 1
MOVE: # 4
[[ 1 -3 -3]
 [ 0 -3 -3]
 [-3  0 -3]]
0 1
Enter the coord . Ex : 0 2 or 1 1
MOVE: # 5
[[ 1  1 -3]
 [ 0 -3 -3]
 [-3  0 -3]]
Enter the coord . Ex : 0 2 or 1 1
MOVE: # 6
[[ 1  1 -3]
 [ 0 -3  0]
 [-3  0 -3]]
0 2
[[ 1  1  1]
 [ 0 -3  0]
 [-3  0 -3]]
WINNER WINNER CHICKEN DINNER
